val lower_c : Located_note.t
val lower_dz_flat : Located_note.t
val lower_d : Located_note.t
val lower_ez_flat : Located_note.t
val lower_e : Located_note.t
val lower_fp : Located_note.t
val lower_fz : Located_note.t
val lower_fp_sharp : Located_note.t
val lower_gz_flat : Located_note.t
val lower_g : Located_note.t
val lower_az_flat : Located_note.t
val lower_a : Located_note.t
val lower_bz_flat : Located_note.t
val lower_bp : Located_note.t
